---
config:
  themeVariables:
    fontSize: 20px
  theme: default
---
flowchart LR
  classDef area fill:#eef6ff,stroke:#3a6ea5,stroke-width:0.6px,font-size:24px;
  classDef soft fill:#fffaf0,stroke:#c77e00,stroke-width:0.8px;
  classDef bigText font-size:24px;

  subgraph Ljudje [Akterji]
    A[Regulator]
    P[Izdelovalec zdravil]
    L[Transporter]
    K[Lekarna]
  end

  subgraph Veriga [Veriga blokov]
    TG[[Pametna pogodba<br/>TrustGraph.sol]]
  end

  subgraph Oraklji [Omrežje orakljev]
    N1[Vozlišče oraklja A]
    N2[Vozlišče oraklja B]
    N3[Vozlišče oraklja C]
    Agg[Agregator]:::soft
  end

  subgraph Viri [Viri podatkov]
    VC[(Shramba dokazil VC)]
    KB[(Baza Fuseki)]
  end
  A -- Zahteva poročila o zaupanju --> TG
  P -- Branje odločitve --> TG
  L -- Branje odločitve --> TG
  K -- Branje odločitve --> TG
  TG -- Zahteva za izračun --> N1
  TG -- Zahteva za izračun --> N2
  TG -- Zahteva za izračun --> N3
  N1 -- Poizvedbe / preverbe --> KB
  N2 -- Poizvedbe / preverbe --> KB
  N3 -- Poizvedbe / preverbe --> KB

  N2 --> VC
  N3 --> VC
  N1 -- Podpisano poročilo --> Agg
  N2 -- Podpisano poročilo --> Agg
  N3 -- Podpisano poročilo --> Agg
  Agg -- Konsenzni rezultat zaupanja --> TG
  Agg -- Ločeni rezultati zaupanja --> TG
  class A,P,L,K,TG,N1,N2,N3,Agg,VC,KB bigText;
  class Ljudje,Veriga,Oraklji,Viri area;